export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const CHANGE_CATEGORY_COLOR = "CHANGE_CATEGORY_COLOR";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
